package modelo;
// Generated 8/out/2019 1:22:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.swing.JOptionPane;

/**
 * Ferias generated by hbm2java
 * 
 *Classe responsável pela gestão das férias do funcionário
 * 
 * @author Firmino Massango
 * @author Silja Ferro
 * @author Wínia Macaringue
 */
@Entity(name="ferias")
public class Ferias {

     @Id
     @Column(name = "id")
     @GeneratedValue
     private int id;
     
     @Column(name = "nome")//, nullable = false, length = 40)
     private String nome;
     
     @Column(name = "apelido")//, length = 15)
     private String apelido;
     
     @Column(name = "dataInicio")//, nullable = false)
     private Date dataInicio;
     
     @Column(name = "dataFim")//, nullable = false)
     private Date dataFim;
     
     @Column(name = "dataActual")
     private Date dataActual;
     
     @Column(name = "diasDeFerias")
     private int diasDeFerias;
     
     @Column(name = "deFerias")
     private boolean deFerias;

     @Column(name = "observacoes")
     private String observacoes;
   
     

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getApelido() {
        return apelido;
    }

    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    
     
    
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    public int getDiasDeFerias() {
        return diasDeFerias;
    }

    public void setDiasDeFerias(int diasDeFerias) {
        this.diasDeFerias = diasDeFerias;
    }
 
    public boolean isDeFerias() {
        return this.deFerias;
    }
    
    public void setDeFerias(boolean deFerias) {
        this.deFerias = deFerias;
    }

    public Date getDataActual() {
        return dataActual;
    }

    public void setDataActual(Date dataActual) {
        this.dataActual = dataActual;
    }

    public String getObservacoes() {
        return observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    

    
    public void verificarFerias(){
        
        if (this.dataInicio.after(dataActual)) 
              this.deFerias = true;
            
            
        else if (this.dataActual.after(dataFim))
              this.deFerias = false;
                
                
    }    
    
    
}
