package modelo;
// Generated 8/out/2019 1:22:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.swing.JOptionPane;

/**
 * Funcionario generated by hbm2java
 * 
 *
 * @author Firmino Massango
 * @author Silja Ferro
 * @author Wínia Macaringue
 * 
 */
@Entity(name = "funcionario")
public class Funcionario{
  
     @Id
     @Column(name = "id")
     @GeneratedValue
     private int id;
     
      @Column(name = "faltas")//,unique = true)//, nullable = false)
     private int nrFaltas;
     
     @Column(name = "nuit")//,unique = true)//, nullable = false)
     private int nuit;
     
     @Column(name = "nome")//, nullable = false, length = 40)
     private String nome;
     
     @Column(name = "apelido")//, length = 15)
     private String apelido;
     
     @Column(name = "dataNascimento")//, nullable = false)
     private Date dataNascimento;
     
     @Column(name = "genero")//, nullable = false)
     private String genero;
     
     @Column(name = "bi",unique = true)// nullable = false, unique. = true, length = 13)
     private String bi;
     
     @Column(name = "endereco")//, nullable = false, length = 100)
     private String endereco;
     
     @Column(name = "numeroTelefone")//, unique = true)//, nullable = false, unique = true)
     private String numeroTelefone;
     
     @Column(name = "email")//, length = 30)
     private String email;

     @Column(name = "salario")//, nullable = false)
     private Double salarioBase;
     
     @Column(name = "dataIngresso")//, nullable = false)
     private Date dataIngresso;
     
     @Column(name = "estado", length = 8)//, nullable = false, length = 8)
     private String estado;
     
     @Column(name = "dataFimDoContracto")//, nullable = false)
     private Date dataFimDoContracto;
     
     @Column(name = "ferias")//, nullable = false)
     private boolean ferias;
     
     @Column(name = "profissao",length = 15)//, nullable = false, length = 15)
     private String profissao;
     
     @Column(name = "nivelAcademico")//, nullable = false, length = 10)
     private String nivelAcademico;
     
     @Column(name = "instituicao")//, nullable = false, length = 100)
     private String instituicao;
     
     @Column(name="competente")//, nullable = false)
     private String competente;
     
     @Column(name="dedicado")//, nullable = false)
     private String dedicado;
     
     @Column(name="disciplinado")//, nullable = false)
     private String disciplinado;
     
     @Column(name="flexivel")//, nullable = false)
     private String flexivel;
     
     @Column(name="formacaoAdequadaAoCargo")//, nullable = false)
     private String formacaoAdequadaAoCargo;
     
     @Column(name="tipoAdmissao")//, nullable = false, length = 16)
     private String tipoDeAdmissao;
     
     @Column(name="obsFalta")
     private String obsFalta;
     
     @Column(name="motivoFalta")
     private String motivo;
     
     
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getNrFaltas() {
        return nrFaltas;
    }

    public void setNrFaltas(int nrFaltas) {
        this.nrFaltas = nrFaltas;
    }

    
    
    public int getNuit() {
        return nuit;
    }

    public void setNuit(int nuit) {
        this.nuit = nuit;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getApelido() {
        return apelido;
    }

    public void setApelido(String apelido) {
        this.apelido = apelido;
    }


    public Date getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getBi() {
        return bi;
    }

    public void setBi(String bi) {
        this.bi = bi;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getNumeroTelefone() {
        return numeroTelefone;
    }

    public void setNumeroTelefone(String numeroTelefone) {
        this.numeroTelefone = numeroTelefone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Double getSalarioBase() {
        return this.salarioBase;
    }
    
    public void setSalarioBase(Double salarioBase) {
        this.salarioBase = salarioBase;
    }
    public Date getDataIngresso() {
        return this.dataIngresso;
    }
    
    public void setDataIngresso(Date dataIngresso) {
        this.dataIngresso = dataIngresso;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getDataFimDoContracto() {
        return this.dataFimDoContracto;
    }
    
    public void setDataFimDoContracto(Date dataFimDoContracto) {
        this.dataFimDoContracto = dataFimDoContracto;
    }
    
    public boolean isFerias() {
        return this.ferias;
    }
    
    public void setFerias(boolean ferias) {
        this.ferias = ferias;
    }
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    public String getNivelAcademico() {
        return nivelAcademico;
    }

    public void setNivelAcademico(String nivelAcademico) {
        this.nivelAcademico = nivelAcademico;
    }

    public String getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }

    public String getCompetente() {
        return competente;
    }

    public void setCompetente(String competente) {
        this.competente = competente;
    }

    public String getDedicado() {
        return dedicado;
    }

    public void setDedicado(String dedicado) {
        this.dedicado = dedicado;
    }

    public String getDisciplinado() {
        return disciplinado;
    }

    public void setDisciplinado(String disciplinado) {
        this.disciplinado = disciplinado;
    }

    public String getFlexivel() {
        return flexivel;
    }

    public void setFlexivel(String flexivel) {
        this.flexivel = flexivel;
    }

    public String getFormacaoAdequadaAoCargo() {
        return formacaoAdequadaAoCargo;
    }

    public void setFormacaoAdequadaAoCargo(String formacaoAdequadaAoCargo) {
        this.formacaoAdequadaAoCargo = formacaoAdequadaAoCargo;
    }

    public String getTipoDeAdmissao() {
        return tipoDeAdmissao;
    }

    public void setTipoDeAdmissao(String tipoDeAdmissao) {
        this.tipoDeAdmissao = tipoDeAdmissao;
    }

    public String getObsFalta() {
        return obsFalta;
    }

    public void setObsFalta(String obsFalta) {
        this.obsFalta = obsFalta;
    }

    public String getMotivo() {
        return motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    
    

    @Override
    public String toString() {
        return getNome();
    }
    
}
