/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controlo.CtrlUser;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Utilizadores;

/**
 *
 * @author whisfirm
 */
public final class Login extends javax.swing.JFrame {

        CtrlUser dao = new CtrlUser();
        
        List utilizadores = new ArrayList();
            List senhas = new ArrayList();
    
    
    /**
     * Creates new form TelaLog
     */
    public Login() {
        initComponents();
        setIcon();
        inicializacao();
    }
    
    public void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("TheClik.png")));
        
    }
    
    public void inicializacao(){
        
        
        for (Utilizadores usr : dao.listar("")) {

            

            utilizadores.add(usr.getUser());
            senhas.add(usr.getSenha());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnConf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setLayout(null);

        txtUser.setBackground(new java.awt.Color(53, 53, 139));
        txtUser.setFont(new java.awt.Font("Clear Sans", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(70, 128, 190, 30);

        txtSenha.setBackground(new java.awt.Color(53, 53, 139));
        txtSenha.setFont(new java.awt.Font("Clear Sans", 1, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSenha.setEchoChar('\u2022');
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(70, 230, 190, 27);

        btnConf.setFont(new java.awt.Font("Clear Sans", 0, 14)); // NOI18N
        btnConf.setText("Entrar");
        btnConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfActionPerformed(evt);
            }
        });
        btnConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfKeyPressed(evt);
            }
        });
        jPanel1.add(btnConf);
        btnConf.setBounds(110, 400, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lOGIN.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -20, 370, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

        txtSenha.requestFocus();

    }//GEN-LAST:event_txtUserActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed

        btnConf.requestFocus();

    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfActionPerformed
        verificacaoCredenciais();
    }//GEN-LAST:event_btnConfActionPerformed

    private void btnConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txtUser.setText("");
            txtSenha.setText("");
            txtUser.requestFocus();
        }
    }//GEN-LAST:event_btnConfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                Login tela = new Login();
                tela.setVisible(true);

                tela.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                 tela.addWindowListener(new WindowAdapter() {

                    public void windowClosing(WindowEvent e) {

                        int resposta = JOptionPane.showConfirmDialog(null, "Realmente deseja encerrar o programa?",
                                "Confirmar", JOptionPane.YES_NO_OPTION);
                        
                        if (resposta == JOptionPane.YES_OPTION) {
                            System.exit(0);
                        } else {
                            tela.setVisible(true);
                        }
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

public void verificacaoCredenciais(){
        
    
    if ((txtUser.getText().equals(utilizadores.get(0))) && (txtSenha.getText().equals(senhas.get(0)))) {

        new TelaPrincipal().setVisible(true);
        dispose();

    }

    if ((txtUser.getText().equals(utilizadores.get(1))) && (txtSenha.getText().equals(senhas.get(1)))) {

        new TelaPrincipalAdmin().setVisible(true);
        dispose();

    }
    
    for (int i = 0; i < utilizadores.size();i++){

        
        
         if (((txtUser.getText().equals(utilizadores.get(i))) && (txtSenha.getText() != senhas.get(i)))){
            
             txtSenha.setText("");
             txtSenha.requestFocus();
        }
           
        
        else if (((txtUser.getText() != utilizadores.get(i)) && (txtSenha.getText().equals(senhas.get(i))))){
            txtUser.setText("");
            txtUser.requestFocus();
        }
            
        else {
            txtUser.setText("");
            txtSenha.setText("");
            txtUser.requestFocus();
        }
    }
    }
}
